version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      FLASK_ENV: development
      DB_USER: myuser
      DB_PASS: mypassword
      DB_NAME: mydatabase
      DB_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
